// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4R8sVWskfXH7luwVDO2NaONpPOjtWFWA',
    appId: '1:722198576166:web:83def23a111abcc88cfae7',
    messagingSenderId: '722198576166',
    projectId: 'stoquer-a6ad4',
    authDomain: 'stoquer-a6ad4.firebaseapp.com',
    storageBucket: 'stoquer-a6ad4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg_OTapt-8_FbIalEE4fTsGVh71vhDBHA',
    appId: '1:722198576166:android:8c4f29fcdcf2d5f38cfae7',
    messagingSenderId: '722198576166',
    projectId: 'stoquer-a6ad4',
    storageBucket: 'stoquer-a6ad4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjepqkgI1JjqIr949_nY5OOG96eMDfk0',
    appId: '1:722198576166:ios:f93da1e9c5a6e1658cfae7',
    messagingSenderId: '722198576166',
    projectId: 'stoquer-a6ad4',
    storageBucket: 'stoquer-a6ad4.firebasestorage.app',
    iosBundleId: 'com.example.stoquer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjepqkgI1JjqIr949_nY5OOG96eMDfk0',
    appId: '1:722198576166:ios:f93da1e9c5a6e1658cfae7',
    messagingSenderId: '722198576166',
    projectId: 'stoquer-a6ad4',
    storageBucket: 'stoquer-a6ad4.firebasestorage.app',
    iosBundleId: 'com.example.stoquer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4R8sVWskfXH7luwVDO2NaONpPOjtWFWA',
    appId: '1:722198576166:web:f8f71a89426586228cfae7',
    messagingSenderId: '722198576166',
    projectId: 'stoquer-a6ad4',
    authDomain: 'stoquer-a6ad4.firebaseapp.com',
    storageBucket: 'stoquer-a6ad4.firebasestorage.app',
  );
}
