platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', { 'Debug'=>:debug, 'Profile'=>:release, 'Release'=>:release }

# ————— Detecta o Flutter SDK via `which flutter` —————
def flutter_root
  flutter_path = `which flutter`.strip
  if flutter_path.empty?
    raise "❌ Flutter não encontrado no PATH. Rode `flutter` neste terminal primeiro."
  end
  File.expand_path('..', File.dirname(flutter_path))
end

require File.join(flutter_root,
                  'packages', 'flutter_tools',
                  'bin', 'podhelper')
flutter_ios_podfile_setup
# ————————————————————————————————————————————

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  
  pod 'Firebase/CoreOnly', $firebase_sdk_version
  pod 'Firebase/Auth',      $firebase_sdk_version
  pod 'Firebase/Firestore', $firebase_sdk_version
  pod 'Firebase/Storage',   $firebase_sdk_version

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
